apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-neobank-api-account-service
  labels:
    app.kubernetes.io/name: neobank-api-account-service
    app.kubernetes.io/instance: wordpress-abcxzy
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cf-neobank-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: neobank-api-account-service
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: neobank-api-account-service
    spec:
      containers:
        - name: cf-neobank-api-account-service
          image: {{ .Values.repository }}/{{ .Values.registry }}:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: neobank-api-account-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cf-neobank-api-account-service
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70